# Generated by Django 6.0.3 on 2026-03-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_priority_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="comment",
            field=models.TextField(blank=True),
        ),
    ]
